[project]
name = "byof"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.121.0",
    "fastapi>=0.141.1",
    "feedparser>=6.0.14",
    "gnews[fulltext]>=0.8.2",
    "imageio>=2.37.4",
    "imageio-ffmpeg>=0.6.0",
    "openai>=2.53.0",
    "pillow>=12.3.0",
    "playwright>=1.62.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "uvicorn>=0.52.1",
]

[dependency-groups]
dev = [
    "datasette>=0.65.2",
    "pytest>=9.1.1",
]
